photo_gallery/photo_gallery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.defaults import page_not_found
from django.views.generic import TemplateView

from .sitemap_config import CollectionSitemap, PhotoSitemap, StaticViewSitemap
from contact.views import ContactMessageCreateView, ContactSuccessView
from photos.views import CollectionView, PhotoDetailView, PhotoListView, SearchView


def custom_404_template(request):
    return page_not_found(request, None)


urlpatterns = [
    path('', PhotoListView.as_view(), name='homepage'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': {'static': StaticViewSitemap,
                                               'collections': CollectionSitemap,
                                               'photos': PhotoSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('contact', ContactMessageCreateView.as_view(), name='contact'),
    path('contact-success', ContactSuccessView.as_view(), name='contact_success'),
    path('search', SearchView.as_view(), name='search'),
    path('photos/<slug:slug>', PhotoDetailView.as_view(), name='photo_detail'),
    path('404', custom_404_template),
    path('<slug:collection_slug>', CollectionView.as_view(), name='collection'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# https://docs.djangoproject.com/en/4.0/howto/static-files/#serving-files-uploaded-by-a-user-during-development

photo_gallery/photos/models.py
from django.contrib import admin
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, validate_slug
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFit


def validate_lowercase(string):
    # https://docs.djangoproject.com/en/4.0/ref/validators/
    lower_str = string.lower()
    if string != lower_str:
        raise ValidationError("All letters must be lowercase.")


class Collection(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(max_length=5000)

    slug_guidelines = "Enter a unique, descriptive URL path (e.g. based on the name) containing " \
                      "only lowercase letters, numbers,  and hyphens (instead of spaces). "

    slug = models.SlugField(max_length=50,
                            unique=True,
                            help_text=slug_guidelines,
                            validators=[validate_slug, validate_lowercase])

    published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("collection", kwargs={"collection_slug": self.slug})

    class Meta:
        ordering = ['name']


class Country(models.Model):
    name = models.CharField(max_length=255, unique=True, validators=[MinLengthValidator(2)])

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = "countries"


class Photo(models.Model):
    img_guidelines = "Upload images with a width of 2000px or greater " \
                     "to avoid low visual quality (e.g. pixelation) on larger screen sizes."

    # https://django-imagekit.readthedocs.io/en/latest/#defining-specs-in-models
    # Avoid storing and serving very large uploaded image files
    large_image = ProcessedImageField(verbose_name="image file",
                                      help_text=img_guidelines,
                                      processors=[ResizeToFit(width=2000)],
                                      format='JPEG',
                                      options={'quality': 80})

    # Use to improve loading performance (photo listings and mobile images)
    small_image = ImageSpecField(source='large_image',
                                 processors=[ResizeToFit(width=550)],
                                 format='JPEG')

    # Display in the admin interface via `thumbnail_img_tag()`
    thumbnail = ImageSpecField(source='large_image',
                               processors=[ResizeToFit(width=150)],
                               format='JPEG')

    @admin.display(description='Thumbnail')
    def thumbnail_img_tag(self):
        return mark_safe('<img src="{}" />'.format(self.thumbnail.url))

    title = models.CharField(max_length=255)

    slug_guidelines = "Enter a unique, descriptive URL path (e.g. based on the title) containing " \
                      "only lowercase letters, numbers,  and hyphens (instead of spaces). "

    slug = models.SlugField(max_length=60,
                            unique=True,
                            help_text=slug_guidelines,
                            validators=[validate_slug, validate_lowercase])

    description = models.TextField(max_length=5000)

    loc_guidelines = "Enter the specific location where the photo was taken."
    location = models.CharField(max_length=255, help_text=loc_guidelines)

    # Country is optional
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)

    date_taken = models.DateField()

    # Collections are optional
    collections = models.ManyToManyField(Collection, blank=True)

    featured = models.BooleanField(default=False)

    published = models.BooleanField(default=True)

    # Use within the XML sitemap
    last_modified = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return "{} ({})".format(self.title, self.slug)

    def get_absolute_url(self):
        return reverse("photo_detail", kwargs={"slug": self.slug})

photo_gallery/photos/views.py
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import DetailView, ListView
from .models import Collection, Photo


class PhotoListView(ListView):
    model = Photo
    paginate_by = 6  # Display 6 photos per page

    def get_filtered_photos(self):
        """Return a filtered queryset of Photos that are published.
        https://docs.djangoproject.com/en/4.0/ref/models/querysets/
        """
        return Photo.objects.filter(published=True)

    def get_sorted_photos(self, qs):
        """Sort and return a Photo queryset depending on the `sort` query string (if applicable).
        https://docs.djangoproject.com/en/4.0/ref/models/querysets/

        Args:
            qs (QuerySet): the (filtered) QuerySet to be sorted.
        """
        # Retrieve `sort` query string value, otherwise None
        sort = self.request.GET.get('sort')
        if sort == "new":
            # Order by descending date (most recent earlier)
            return qs.order_by('-date_taken')

        elif sort == "old":
            # Order by ascending date (oldest earlier)
            return qs.order_by('date_taken')

        # Order by featured (featured at start) then by descending date (most recent earlier)
        return qs.order_by('-featured', '-date_taken')

    def get_queryset(self):
        filtered_qs = self.get_filtered_photos()
        return self.get_sorted_photos(filtered_qs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sorting'] = self.request.GET.get('sort', 'default')
        return context


class CollectionView(PhotoListView):
    template_name = "photos/collection.html"

    def get_filtered_photos(self):
        """Return a filtered queryset of Photos that are in the collection.
        https://docs.djangoproject.com/en/4.0/ref/models/querysets/
        """
        collection = get_object_or_404(Collection, slug=self.kwargs['collection_slug'])
        if not collection.published:
            raise Http404()

        return Photo.objects.filter(published=True, collections__in=[collection])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['collection'] = get_object_or_404(Collection, slug=self.kwargs['collection_slug'])
        return context


class SearchView(PhotoListView):
    template_name = "photos/search.html"

    def get_filtered_photos(self):
        """Return a filtered queryset of Photos whose primary content includes the search query.
        https://docs.djangoproject.com/en/4.0/ref/models/querysets/
        """
        query = self.request.GET.get('query', None)
        if query is not None:
            # https://docs.djangoproject.com/en/4.0/topics/db/queries/#complex-lookups-with-q-objects
            lookup = Q(title__icontains=query) | \
                     Q(description__icontains=query) | \
                     Q(location__icontains=query)

            return Photo.objects.filter(lookup)

        return Photo.objects.filter(published=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_query'] = self.request.GET.get('query', '')
        return context

    def get(self, request, *args, **kwargs):
        query = request.GET.get('query', None)
        if query is None:
            return redirect('homepage')

        return super().get(request, *args, **kwargs)


class PhotoDetailView(DetailView):
    model = Photo
    # Return a 404 if the photo isn't published
    queryset = Photo.objects.filter(published=True)

photo_gallery/photos/templates/photos/collection.html
{% extends "photos/photo_list.html" %}

{% block head_content_tags %}
<title>{{ collection.name }} | Chris Mastris</title>
{# Include page query string if present and >1 (1 is duplicate); other queries excluded #}
<link rel="canonical" href="{{ absolute_root_url }}{{ request.path }}{% if page_obj.number > 1 %}?page={{ page_obj.number }}{% endif %}">
<meta name="description" content="{{ collection.description }}">
<meta property="og:url" content="{{ absolute_root_url }}{{ request.path }}{% if page_obj.number > 1 %}?page={{ page_obj.number }}{% endif %}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{ collection.name }}">
<meta property="og:description" content="{{ collection.description }}">
{% endblock %}

{% block header_content %}
<h1 class="display-4">{{ collection.name }}</h1>
<div class="row justify-content-lg-center mt-4">
  <div class="col-lg-9">
    <p>{{ collection.description }}</p>
  </div>
</div>
{% endblock header_content %}

photo_gallery/photos/templates/photos/photo_detail.html
{% extends "base.html" %}
{% block head_content_tags %}
<title>{{ photo.title }} | Chris Mastris</title>
<link rel="canonical" href="{{ absolute_root_url }}{{ request.path }}">
<meta name="description" content="View the photo titled '{{ photo.title }}'. Location: {{ photo.location }}. Date taken: {{ photo.date_taken|date:"F Y" }}.">
<meta property="og:url" content="{{ absolute_root_url }}{{ request.path }}">
<meta property="og:type" content="website">
<meta property="og:title" content="{{ photo.title }}">
<meta property="og:description" content="View the photo titled '{{ photo.title }}'. Location: {{ photo.location }}. Date taken: {{ photo.date_taken|date:"F Y" }}.">
<meta property="og:image" content="{{ absolute_root_url }}{{ photo.large_image.url }}">
{% endblock %}

{% block content %}
<div class="container-lg text-center">
  <img srcset="{{ photo.small_image.url }} 550w,
               {{ photo.large_image.url }} 2000w"
       sizes="(max-width:600px) 95vw, 80vw"
       src="{{ photo.large_image.url }}"
       class="img-fluid border border-muted border-4" alt="{{ photo.title }}">
</div>
<div class="container-lg text-center">  
  <h1 class="display-6 pt-4">{{ photo.title }}</h1>
  <div class="row justify-content-md-center pt-3 pb-4 gy-2 mb-lg-3 text-success">
    <div class="col-md-auto px-5">
      <i class="bi bi-geo-alt text-dark"></i> {{ photo.location }}
    </div>
    <div class="col-md-auto px-5">
      <i class="bi bi-calendar-event text-dark px-1"></i> {{ photo.date_taken|date:"F Y" }}
    </div>
  </div>
  <div class="row justify-content-lg-center">
    <div class="col-lg-9">
      {{ photo.description|linebreaks }}
      {% if photo.collections.all|length > 0 %}
      <div class="row justify-content-md-center py-4 gx-2 lh-lg">
        <div class="col-md-auto">
          <span class="fw-bold fst-italic">Collections:</span>
        </div>
        <div class="col-md-auto">
          {% for collection in photo.collections.all %}
          <span class="px-1">
            <a class="link-success" href="{{ collection.get_absolute_url }}">{{ collection.name }}</a>
          </span>
          {% if not forloop.last %}<span>|</span>{% endif %}
          {% endfor %}
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

photo_gallery/photos/templates/photos/photo_list.html
{% extends "base.html" %}

{% block head_content_tags %}
<title>Photo Gallery | Chris Mastris</title>
{# Include page query string if present and >1 (1 is duplicate); other queries excluded #}
<link rel="canonical" href="{{ absolute_root_url }}{{ request.path }}{% if page_obj.number > 1 %}?page={{ page_obj.number }}{% endif %}">
<meta name="description" content="A Django photo gallery website by Chris Mastris.">
<meta property="og:url" content="{{ absolute_root_url }}{{ request.path }}{% if page_obj.number > 1 %}?page={{ page_obj.number }}{% endif %}">
<meta property="og:type" content="website">
<meta property="og:title" content="Photo Gallery">
<meta property="og:description" content="A Django photo gallery website by Chris Mastris.">
{% endblock head_content_tags %}

{% block content %}
<div class="container-lg text-center">
  
  {% block header_content %}
  <div class="mb-5">
    <h1 class="display-4">
      Photography by Chris Mastris
    </h1>
  </div>
  {% endblock header_content %}

  {% block sorting_dropdown %}
  {% if photo_list|length > 2 %}
  <div class="row justify-content-lg-center pt-4 mt-4">
    <div class="col-md-10">
      <div class="dropdown text-end">
        <button class="btn btn-success btn-sm p-2 dropdown-toggle" id="dropdownMenuButton" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Sort by...
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <li>
            {% if sorting == 'default' %}
            <a class="dropdown-item active" href="#" aria-current="true">Featured (default)</a>
            {% else %}
            <a class="dropdown-item" href="{{ request.path }}">Featured (default)</a>
            {% endif %}
          </li>
          <li>
            {% if sorting == 'new' %}
            <a class="dropdown-item active" href="#" aria-current="true">Newest</a>
            {% else %}
            <a class="dropdown-item" href="?sort=new">Newest</a>
            {% endif %}
          </li>
          <li>
            {% if sorting == 'old' %}
            <a class="dropdown-item active" href="#" aria-current="true">Oldest</a>
            {% else %}
            <a class="dropdown-item" href="?sort=old">Oldest</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </div>
  {% endif %}
  {% endblock sorting_dropdown %}
  
  {# Photo listings #}
  {% if photo_list|length == 0 %}
  {# Display error message instead of empty photo list #}
  <div class="my-5 py-5">
    <p class="fs-5 py-4">Sorry, no photos were found.</p>
  </div>
  {% else %}
  <div class="mt-1 mb-5">
    
    <div class="row justify-content-lg-center">
      {% for photo in photo_list %}
      <div class="col-lg-5 my-3 my-lg-4 gx-3 mx-lg-3 mx-xxl-5 justify-content-center d-flex">
        <div class="border bg-light">
          <a href="{{ photo.get_absolute_url }}">
            <img src="{{ photo.small_image.url }}"
                 alt="{{ photo.title }}"
                 class="img-fluid">
          </a>
          {% if photo.featured %}
          <div class="py-1 px-3 bg-success border-top border-bottom border-dark border-1">
            <p class="my-0 text-end text-uppercase h6 text-white">Featured</p>
          </div>
          {% else %}
          <div class="border-bottom border-success border-4"></div>
          {% endif %}
          <p class="pt-4 pb-0 px-3">
            <a class="h5 text-dark text-decoration-none" href="{{ photo.get_absolute_url }}">
              {{ photo.title }}
            </a>
          </p>
          <div class="pb-3 text-success">
            <i class="bi bi-calendar-event px-1"></i> {{ photo.date_taken|date:"F Y" }}
          </div>
        </div>
      </div>
    {% if forloop.counter == 2 or forloop.counter == 4 %} {# 2 photos per row #}
    </div>

    <div class="row justify-content-lg-center">
    {% endif %}{% endfor %}
    </div>
  
  </div>
  {% endif %}{# End of `photo_list|length == 0` conditional block #}

  {# Pagination #}
  {% if page_obj.paginator.num_pages > 1 %}
  <div class="row justify-content-center d-flex align-items-center mb-5">
    <div class="col-5 text-end fs-4">
      <span class="px-3 px-md-5">
      {% if page_obj.has_previous %}
        <a class="link-secondary" href="?{% if search_query %}query={{ search_query }}&{% endif %}page=1{% if sorting != 'default' %}&sort={{ sorting }}{% endif %}">&laquo;</a>
      </span>
      <span class="px-3 px-md-5">
        <a class="link-secondary" href="?{% if search_query %}query={{ search_query }}&{% endif %}page={{ page_obj.previous_page_number }}{% if sorting != 'default' %}&sort={{ sorting }}{% endif %}">{{ page_obj.previous_page_number }}</a>
      {% endif %}
      </span>
    </div>

    <div class="col-2 text-center">
      <span class="h1" aria-current="page">{{ page_obj.number }}</span>
    </div>

    <div class="col-5 text-start fs-4">
      <span class="px-3 px-md-5">
      {% if page_obj.has_next %}
        <a class="link-secondary" href="?{% if search_query %}query={{ search_query }}&{% endif %}page={{ page_obj.next_page_number }}{% if sorting != 'default' %}&sort={{ sorting }}{% endif %}">{{ page_obj.next_page_number }}</a>
      </span>
      <span class="px-3 px-md-5">
        <a class="link-secondary" href="?{% if search_query %}query={{ search_query }}&{% endif %}page={{ page_obj.paginator.num_pages }}{% if sorting != 'default' %}&sort={{ sorting }}{% endif %}">&raquo;</a>
      {% endif %}
      </span>
    </div>
  </div>
  {% endif %}

</div>
{% endblock content %}

photo_gallery/photos/templates/photos/search.html
{% extends "photos/photo_list.html" %}

{% block head_content_tags %}
<title>Search Results: '{{ search_query }}' | Chris Mastris</title>
<link rel="canonical" href="{{ absolute_root_url }}{{ request.path }}">
<meta name="description" content="Search Results: '{{ search_query }}'">
<meta property="og:url" content="{{ absolute_root_url }}{{ request.path }}?query={{ search_query }}{% if page_obj.number > 1 %}&page={{ page_obj.number }}{% endif %}">
<meta property="og:type" content="website">
<meta property="og:title" content="Search Results: '{{ search_query }}'">
<meta property="og:description" content="Search results for '{{ search_query }}'.">
{% endblock head_content_tags %}
{% block robots %}<meta name="robots" content="noindex, nofollow">{% endblock %}

{% block header_content %}
<div class="mb-5">
  <h1 class="display-4">
    Search results: "{{ search_query }}"
  </h1>
</div>
{% endblock header_content %}

{% block sorting_dropdown %}{# Don't provide sorting options for search results #}{% endblock %}