photo_gallery/photo_gallery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from django.views.defaults import page_not_found
from django.views.generic import TemplateView

from .sitemap_config import CollectionSitemap, PhotoSitemap, StaticViewSitemap
from contact.views import ContactMessageCreateView, ContactSuccessView
from photos.views import CollectionView, PhotoDetailView, PhotoListView, SearchView


def custom_404_template(request):
    return page_not_found(request, None)


urlpatterns = [
    path('', PhotoListView.as_view(), name='homepage'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('sitemap.xml', sitemap, {'sitemaps': {'static': StaticViewSitemap,
                                               'collections': CollectionSitemap,
                                               'photos': PhotoSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),
    path('admin/', admin.site.urls),
    path('contact', ContactMessageCreateView.as_view(), name='contact'),
    path('contact-success', ContactSuccessView.as_view(), name='contact_success'),
    path('search', SearchView.as_view(), name='search'),
    path('photos/<slug:slug>', PhotoDetailView.as_view(), name='photo_detail'),
    path('404', custom_404_template),
    path('<slug:collection_slug>', CollectionView.as_view(), name='collection'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# https://docs.djangoproject.com/en/4.0/howto/static-files/#serving-files-uploaded-by-a-user-during-development

photo_gallery/nav/models.py
from django.db import models


class NavSection(models.Model):
    dropdown_label_guidelines = "Enter the clickable dropdown menu text, if applicable. " \
                                "Otherwise, leave blank if the navigation menu section contains " \
                                "only a single link rather than a dropdown menu."

    dropdown_label = models.CharField(max_length=50, blank=True,
                                      help_text=dropdown_label_guidelines)

    section_order_guidelines = "Select the ordering of the navigation menu section, where '1st' " \
                               "refers to the leftmost (desktop) or top (mobile) position."

    ORDER_CHOICES = [
        (1, '1st'),
        (2, '2nd'),
        (3, '3rd'),
        (4, '4th'),
        (5, '5th'),
        (6, '6th'),
    ]

    section_order = models.IntegerField(choices=ORDER_CHOICES, blank=False, unique=True,
                                        help_text=section_order_guidelines)

    def __str__(self):
        return "Navigation Section " + str(self.section_order)

    class Meta:
        ordering = ['section_order']
        verbose_name = "Navigation Section"


class NavLink(models.Model):
    link_text_guidelines = "Enter the clickable link text (anchor text)."
    link_text = models.CharField(max_length=50, help_text=link_text_guidelines)

    link_url_guidelines = "Enter the link destination relative URL. E.g. if the full URL is " \
                          "'https://www.example.com/photos/this-photo' then the relative URL is " \
                          "'/photos/this-photo'."

    link_url = models.CharField("link URL", max_length=255, help_text=link_url_guidelines)

    vertical_order_guidelines = "Select the vertical ordering of the link in the dropdown menu " \
                                "(if applicable), where '1st' refers to the top position."
    ORDER_CHOICES = [
        (0, 'N/A'),
        (1, '1st'),
        (2, '2nd'),
        (3, '3rd'),
        (4, '4th'),
        (5, '5th'),
        (6, '6th'),
        (7, '7th'),
        (8, '8th'),
    ]

    vertical_order = models.IntegerField(choices=ORDER_CHOICES, blank=False, default=0,
                                         help_text=vertical_order_guidelines)

    nav_section = models.ForeignKey(NavSection, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.link_text

    class Meta:
        verbose_name = "Navigation Link"

photo_gallery/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block head_content_tags %}
  {% with title="Photo Gallery | Chris Mastris" description="A Django photo gallery website by Chris Mastris." %}
  <title>{{ title }}</title>
  <link rel="canonical" href="{{ absolute_root_url }}{{ request.path }}">
  <meta name="description" content="{{ description }}">
  <meta property="og:url" content="{{ absolute_root_url }}{{ request.path }}">
  <meta property="og:type" content="website">
  <meta property="og:title" content="{{ title }}">
  <meta property="og:description" content="{{ description }}">
  {% endwith %}
  {% endblock %}
  {% block robots %}{% endblock %}
  <link rel="icon" href="{% static 'favicon.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>

<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
    <div class="container-fluid">
      <a class="navbar-brand mb-0 me-lg-4 h1" href="{% url 'homepage' %}">Photo Gallery</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
          {% for section in nav_sections %}
          {# https://docs.djangoproject.com/en/4.0/topics/db/queries/#following-relationships-backward #}
          {% if section.navlink_set.all|length > 1 %}
          <li class="nav-item dropdown pb-1 pb-lg-0 px-lg-1">
            <a class="nav-link dropdown-toggle" href="#" id="navbarSection{{ forloop.counter }}DropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ section.dropdown_label }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarSection{{ forloop.counter }}DropdownMenuLink">
              {% for link in section.navlink_set.all|dictsort:"vertical_order" %}
              {% if link.link_url == request.path %}
              <li><a class="dropdown-item py-2 text-success" aria-current="page" href="{{ link.link_url }}">{{ link.link_text }}</a></li>
              {% else %}
              <li><a class="dropdown-item py-2" href="{{ link.link_url }}">{{ link.link_text }}</a></li>
              {% endif %}
              {% endfor %}
            </ul>
          </li>
          {% else %}{# NavSection with a single NavLink (no dropdown) #}
          {% with link=section.navlink_set.all.0 %}
          <li class="nav-item pb-1 pb-lg-0 px-lg-1">
            {% if link.link_url == request.path %}
            <a class="nav-link active" aria-current="page" href="{{ link.link_url }}">{{ link.link_text }}</a>
            {% else %}
            <a class="nav-link" href="{{ link.link_url }}">{{ link.link_text }}</a>
            {% endif %}
          </li>
          {% endwith %}
          {% endif %}
          {% endfor %}
        </ul>
        <form class="d-flex my-3 my-lg-0 me-lg-5" action="{% url 'search' %}" method="get" role="search">
          <label class="visually-hidden" for="search-input">Search photos</label>
          <input class="form-control rounded-0 border-secondary" id="search-input" type="search" name="query" placeholder="Search photos...">
          <button class="btn btn-light rounded-0 border-secondary" type="submit">
            <i class="bi bi-search"></i>
          </button>
        </form>
      </div>
    </div>
  </nav>
</header>

<main>
  {% block content %}{% endblock %}
</main>

<footer>
  <div class="container-fluid mt-4 text-center text-muted">
    <hr>
    <p class="py-2 fst-italic">View this project on 
      <a class="link-success"
          href="https://github.com/Cmastris/django_photo_gallery" 
          target="_blank" 
          rel="noopener">GitHub</a>
    </p>
  </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>